# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_screen_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_window(object):
    def setupUi(self, register_window):
        register_window.setObjectName("register_window")
        register_window.resize(370, 243)
        register_window.setStyleSheet("background-color: rgb(93, 166, 200)")
        self.centralwidget = QtWidgets.QWidget(register_window)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_app_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_app_name.setFont(font)
        self.label_app_name.setStyleSheet("background-color: #FFFFE0")
        self.label_app_name.setObjectName("label_app_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_app_name)
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setStyleSheet("background-color: #FFFFFF")
        self.login.setObjectName("login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.login)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setStyleSheet("background-color: #FFFFFF")
        self.password.setObjectName("password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.password)
        self.confirm_password = QtWidgets.QLineEdit(self.centralwidget)
        self.confirm_password.setStyleSheet("background-color: #FFFFFF")
        self.confirm_password.setObjectName("confirm_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.confirm_password)
        self.date_birth = QtWidgets.QDateEdit(self.centralwidget)
        self.date_birth.setStyleSheet("background-color: #FFFFFF")
        self.date_birth.setObjectName("date_birth")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.date_birth)
        self.okey = QtWidgets.QPushButton(self.centralwidget)
        self.okey.setStyleSheet("background-color: rgb(0, 170, 0)")
        self.okey.setObjectName("okey")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.okey)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.cancel.setObjectName("cancel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cancel)
        register_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)

    def retranslateUi(self, register_window):
        _translate = QtCore.QCoreApplication.translate
        register_window.setWindowTitle(_translate("register_window", "MainWindow"))
        self.label_app_name.setText(_translate("register_window", "Регистрация"))
        self.okey.setText(_translate("register_window", "Ок"))
        self.cancel.setText(_translate("register_window", "Отмена"))


class RegisterCall(QtWidgets.QMainWindow):
    def __init__(self):
        super(RegisterCall, self).__init__()
        self.ui = Ui_register_window()
        self.ui.setupUi(self)
        self.init_UI()

    def init_UI(self):
        self.setWindowTitle('Окно регистрации')
        self.ui.login.setPlaceholderText('имя пользователя')
        self.ui.password.setPlaceholderText('пароль')
        self.ui.confirm_password.setPlaceholderText('подтвердите пароль')
        # post data to db
        self.ui.cancel.clicked.connect(self.go_back_to_main_from_register)

    def go_back_to_main_from_register(self):
        pass

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     register_window = QtWidgets.QMainWindow()
#     ui = Ui_register_window()
#     ui.setupUi(register_window)
#     register_window.show()
#     sys.exit(app.exec_())
